[build]
  base = "FixitCSV"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build/client"

[functions]
  directory = "build/server"
  node_bundler = "nft"

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
