name = "FixitCSV"
client_id = "ae643eaf470a54b579b814b2a513eadd"
application_url = "https://fixitcsv.uplifttechnologies.pro"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "read_products"

[auth]
redirect_urls = [
  "https://fixitcsv-prod.netlify.app/auth/callback",
  "https://fixitcsv-prod.netlify.app/auth/shopify/callback",
  "https://fixitcsv-prod.netlify.app/api/auth/callback",
  "https://fixitcsv.uplifttechnologies.pro/auth/callback",
  "https://fixitcsv.uplifttechnologies.pro/auth/shopify/callback",
  "https://fixitcsv.uplifttechnologies.pro/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks"

[pos]
embedded = false
