# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b8c9d31f63a181ca1051d218f6ec2cb7"
name = "fixit csv: AI Powered"
application_url = "https://fixitcsv.uplifttechnologies.pro/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[webhooks.privacy_compliance]
customer_deletion_url = "https://fixitcsv.uplifttechnologies.pro/webhooks"
customer_data_request_url = "https://fixitcsv.uplifttechnologies.pro/webhooks"
shop_deletion_url = "https://fixitcsv.uplifttechnologies.pro/webhooks"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://fixitcsv.uplifttechnologies.pro/auth/callback", "https://fixitcsv.uplifttechnologies.pro/auth/login" ]

[pos]
embedded = false
