name = "QuoteLoop"
client_id = "c0a7f6741dfc891c848bba84360c66da"
application_url = "https://quoteloop.uplifttechnologies.pro"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[access_scopes]
scopes = "read_draft_orders,write_draft_orders,read_customers"

[auth]
redirect_urls = [ "https://quoteloop.uplifttechnologies.pro/auth/callback" ]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks"

[pos]
embedded = false
