name = "QuoteLoop"
client_id = "fc83b2d79a0791b27995f678fb80b614"
application_url = "https://quoteloop.uplifttechnologies.pro"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[access_scopes]
scopes = "read_draft_orders,write_draft_orders,read_customers"

[auth]
redirect_urls = [
  "https://quoteloop.uplifttechnologies.pro/auth/callback",
  "https://quoteloop.uplifttechnologies.pro/auth/shopify/callback",
  "https://quoteloop.uplifttechnologies.pro/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks"

[webhooks.privacy_compliance]
customer_deletion_url = "https://quoteloop.uplifttechnologies.pro/webhooks"
customer_data_request_url = "https://quoteloop.uplifttechnologies.pro/webhooks"
shop_deletion_url = "https://quoteloop.uplifttechnologies.pro/webhooks"

[pos]
embedded = false
