name = "CustomsReady Lite"
client_id = "b401118ff3d466cd8ac36857e7ac845f"
application_url = "https://customsready.uplifttechnologies.pro"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[access_scopes]
scopes = "read_products,read_orders"

[auth]
redirect_urls = [
  "https://customsready-prod.netlify.app/auth/callback",
  "https://customsready-prod.netlify.app/auth/shopify/callback",
  "https://customsready-prod.netlify.app/api/auth/callback",
  "https://customsready.uplifttechnologies.pro/auth/callback",
  "https://customsready.uplifttechnologies.pro/auth/shopify/callback",
  "https://customsready.uplifttechnologies.pro/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["customers/data_request"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["customers/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["shop/redact"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["products/create"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["products/update"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

[pos]
embedded = false
