/**
 * app.audit.$auditId.pdf.jsx
 *
 * Resource route (no default export / no UI) that generates and streams
 * a PDF version of an audit report.
 *
 * Source requirement: "Generate PDF/email report"
 */
import { authenticate } from "../../shopify.server";
import { prisma } from "../../db.server";
import { generatePdfReport } from "../../lib/pdf/report-pdf.server";

export const loader = async ({ request, params }) => {
  const { session } = await authenticate.admin(request);
  const shop = session.shop;
  const { auditId } = params;

  const audit = await prisma.auditRun.findUnique({
    where: { id: auditId },
  });

  if (!audit || audit.shop !== shop) {
    throw new Response("Audit not found", { status: 404 });
  }

  if (audit.status !== "complete") {
    throw new Response("Audit is not complete", { status: 400 });
  }

  let appResults = [];
  let liquidResults = [];
  let summary = {};

  try { appResults = JSON.parse(audit.appResults); } catch {}
  try { liquidResults = JSON.parse(audit.liquidResults); } catch {}
  try { summary = JSON.parse(audit.summary); } catch {}

  const report = {
    shop: audit.shop,
    generatedAt: audit.createdAt,
    activeTheme: {
      id: audit.themeId ?? "",
      name: audit.themeName ?? "Unknown",
    },
    appResults,
    liquidResults,
    summary,
    disclaimer: [
      "IMPORTANT: This report is generated by automated pattern matching and database lookup.",
      `${summary.appsNotInDatabase} of ${summary.totalAppsScanned} installed apps were not found in the compatibility database and are marked "unknown."`,
      "An all-clear result does not guarantee your store will be unaffected by the New Customer Accounts migration.",
      "Always test the migration in a development store and verify compatibility with app vendors directly before switching.",
    ].join(" "),
  };

  const pdfBuffer = await generatePdfReport(report);
  const filename = `nca-audit-${auditId}-${new Date().toISOString().slice(0, 10)}.pdf`;

  return new Response(pdfBuffer, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="${filename}"`,
      "Content-Length": String(pdfBuffer.length),
    },
  });
};
