[build]
  base = "Craftline"
  command = "npx prisma generate && pnpm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "build/server"
  node_bundler = "nft"
  included_files = ["build/server/**"]

[[headers]]
  for = "/build/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
